import os
from groq import Groq
from schema_extractor import get_schema_text

import streamlit as st
client = Groq(api_key=st.secrets.get("GROQ_API_KEY", os.environ.get("GROQ_API_KEY")))

# Get the live schema from your MySQL database
SCHEMA_TEXT = get_schema_text()

# --- Build the system prompt ---
SYSTEM_PROMPT = f"""You are an expert MySQL query generator.

You will be given a database schema and a user's question in plain English.
Your job is to convert the question into a single, valid MySQL SQL query.

RULES:
- Output ONLY the SQL query. No explanations, no markdown, no ```sql``` fences.
- Use only the tables and columns listed in the schema below. Do not invent column names.
- Always use proper JOINs when the question requires data from multiple tables.
- If the question is ambiguous, make the most reasonable assumption.
- Never use DROP, DELETE, UPDATE, INSERT, or ALTER statements. Only SELECT queries are allowed.

DATABASE SCHEMA:
{SCHEMA_TEXT}

EXAMPLES:

Question: Show me all customers from Chicago
SQL: SELECT * FROM customers WHERE city = 'Chicago';

Question: What is the total sales for each category?
SQL: SELECT cat.category_name, SUM(oi.sales_per_order) AS total_sales
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN categories cat ON p.category_id = cat.category_id
GROUP BY cat.category_name;

Question: List the top 5 customers by total profit
SQL: SELECT c.customer_id, c.first_name, c.last_name, SUM(oi.profit_per_order) AS total_profit
FROM order_items oi
JOIN orders o ON oi.order_id = o.order_id
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_profit DESC
LIMIT 5;

Question: How many orders were delivered late?
SQL: SELECT COUNT(*) FROM orders WHERE delivery_status = 'Late delivery';
"""


def generate_sql(user_question: str) -> str:
    """
    Takes a plain English question and returns a SQL query generated by Groq.
    """
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_question}
        ],
        temperature=0  # keep it deterministic — we want consistent SQL, not creative SQL
    )

    sql_query = response.choices[0].message.content.strip()

    # Safety cleanup: sometimes models still wrap output in ```sql fences despite instructions
    sql_query = sql_query.replace("```sql", "").replace("```", "").strip()

    return sql_query


# --- Quick test ---
if __name__ == "__main__":
    test_questions = [
        "Show me all customers from Chicago",
        "What is the total sales for each category?",
        "Which region has the highest profit?",
        "Show me the top 3 products by quantity sold",
        "How many orders had late delivery in each shipping type?"
    ]

    for q in test_questions:
        print("=" * 60)
        print("Question:", q)
        sql = generate_sql(q)
        print("Generated SQL:\n", sql)
        
        
def fix_sql(user_question: str, broken_sql: str, error_message: str) -> str:
    """
    Sends the failed SQL and its error back to the LLM, asking it to fix it.
    """
    fix_prompt = f"""The following SQL query failed when executed against the database.

Original question: {user_question}

SQL that failed:
{broken_sql}

Error message from the database:
{error_message}

Fix the SQL query so it runs correctly. Follow the same rules as before:
- Output ONLY the corrected SQL query, nothing else.
- Use only tables and columns from the schema provided earlier.
- Only SELECT statements are allowed.
"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": fix_prompt}
        ],
        temperature=0
    )

    fixed_sql = response.choices[0].message.content.strip()
    fixed_sql = fixed_sql.replace("```sql", "").replace("```", "").strip()

    return fixed_sql